
FROM pypy:2
MAINTAINER Fanf <fanf@fanf>

RUN apt-get update 
RUN apt-get -y install openssh-server toilet

RUN pip install twisted 

COPY wolfenscii_client.py /
COPY wolfenscii /wolfenscii

RUN mkdir /var/run/sshd

RUN useradd -m wolf
RUN passwd -d wolf

RUN echo '#!/bin/sh \ncd / && pypy /wolfenscii_client.py' > run.sh
RUN chmod +x /run.sh


RUN sed -i 's/^root.*/root:x:0:0::\/root:\/usr\/sbin\/nologin/' /etc/passwd 
RUN sed -i 's/^wolf.*/wolf:x:1000:1000::\/home\/wolf:\/run.sh/' /etc/passwd 
RUN sed -i 's/^PermitEmptyPasswords.*/PermitEmptyPasswords yes/' /etc/ssh/sshd_config 
RUN sed -i 's/^UsePAM.*/UsePAM no/' /etc/ssh/sshd_config 


EXPOSE 22
CMD /usr/sbin/sshd -D 

