
FROM pypy:2
MAINTAINER Fanf <fanf@fanf>

RUN apt-get update 
RUN apt-get -y install toilet

RUN pip install twisted 

COPY wolfenscii_client.py /
COPY wolfenscii /wolfenscii
CMD pypy wolfenscii_client.py

